/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ShellVisitorsRouteImport } from './routes/_shell/visitors'
import { Route as ShellTeamRouteImport } from './routes/_shell/team'
import { Route as ShellSettingsRouteImport } from './routes/_shell/settings'
import { Route as ShellHelpdeskRouteImport } from './routes/_shell/helpdesk'
import { Route as ShellFloorRouteImport } from './routes/_shell/floor'
import { Route as ShellEventsRouteImport } from './routes/_shell/events'
import { Route as ShellDashboardRouteImport } from './routes/_shell/dashboard'
import { Route as ShellCrmRouteImport } from './routes/_shell/crm'
import { Route as ShellContractsRouteImport } from './routes/_shell/contracts'
import { Route as ShellClientsRouteImport } from './routes/_shell/clients'
import { Route as ShellBookingsRouteImport } from './routes/_shell/bookings'
import { Route as ShellBillingRouteImport } from './routes/_shell/billing'
import { Route as ShellAnalyticsRouteImport } from './routes/_shell/analytics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellVisitorsRoute = ShellVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTeamRoute = ShellTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHelpdeskRoute = ShellHelpdeskRouteImport.update({
  id: '/helpdesk',
  path: '/helpdesk',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFloorRoute = ShellFloorRouteImport.update({
  id: '/floor',
  path: '/floor',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEventsRoute = ShellEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCrmRoute = ShellCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => ShellRoute,
} as any)
const ShellContractsRoute = ShellContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => ShellRoute,
} as any)
const ShellClientsRoute = ShellClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBookingsRoute = ShellBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBillingRoute = ShellBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAnalyticsRoute = ShellAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/billing': typeof ShellBillingRoute
  '/bookings': typeof ShellBookingsRoute
  '/clients': typeof ShellClientsRoute
  '/contracts': typeof ShellContractsRoute
  '/crm': typeof ShellCrmRoute
  '/dashboard': typeof ShellDashboardRoute
  '/events': typeof ShellEventsRoute
  '/floor': typeof ShellFloorRoute
  '/helpdesk': typeof ShellHelpdeskRoute
  '/settings': typeof ShellSettingsRoute
  '/team': typeof ShellTeamRoute
  '/visitors': typeof ShellVisitorsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/billing': typeof ShellBillingRoute
  '/bookings': typeof ShellBookingsRoute
  '/clients': typeof ShellClientsRoute
  '/contracts': typeof ShellContractsRoute
  '/crm': typeof ShellCrmRoute
  '/dashboard': typeof ShellDashboardRoute
  '/events': typeof ShellEventsRoute
  '/floor': typeof ShellFloorRoute
  '/helpdesk': typeof ShellHelpdeskRoute
  '/settings': typeof ShellSettingsRoute
  '/team': typeof ShellTeamRoute
  '/visitors': typeof ShellVisitorsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/analytics': typeof ShellAnalyticsRoute
  '/_shell/billing': typeof ShellBillingRoute
  '/_shell/bookings': typeof ShellBookingsRoute
  '/_shell/clients': typeof ShellClientsRoute
  '/_shell/contracts': typeof ShellContractsRoute
  '/_shell/crm': typeof ShellCrmRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/events': typeof ShellEventsRoute
  '/_shell/floor': typeof ShellFloorRoute
  '/_shell/helpdesk': typeof ShellHelpdeskRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/team': typeof ShellTeamRoute
  '/_shell/visitors': typeof ShellVisitorsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/billing'
    | '/bookings'
    | '/clients'
    | '/contracts'
    | '/crm'
    | '/dashboard'
    | '/events'
    | '/floor'
    | '/helpdesk'
    | '/settings'
    | '/team'
    | '/visitors'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/billing'
    | '/bookings'
    | '/clients'
    | '/contracts'
    | '/crm'
    | '/dashboard'
    | '/events'
    | '/floor'
    | '/helpdesk'
    | '/settings'
    | '/team'
    | '/visitors'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/login'
    | '/_shell/analytics'
    | '/_shell/billing'
    | '/_shell/bookings'
    | '/_shell/clients'
    | '/_shell/contracts'
    | '/_shell/crm'
    | '/_shell/dashboard'
    | '/_shell/events'
    | '/_shell/floor'
    | '/_shell/helpdesk'
    | '/_shell/settings'
    | '/_shell/team'
    | '/_shell/visitors'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/visitors': {
      id: '/_shell/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof ShellVisitorsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/team': {
      id: '/_shell/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof ShellTeamRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/helpdesk': {
      id: '/_shell/helpdesk'
      path: '/helpdesk'
      fullPath: '/helpdesk'
      preLoaderRoute: typeof ShellHelpdeskRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/floor': {
      id: '/_shell/floor'
      path: '/floor'
      fullPath: '/floor'
      preLoaderRoute: typeof ShellFloorRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/events': {
      id: '/_shell/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof ShellEventsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/crm': {
      id: '/_shell/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof ShellCrmRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/contracts': {
      id: '/_shell/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ShellContractsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/clients': {
      id: '/_shell/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ShellClientsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/bookings': {
      id: '/_shell/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof ShellBookingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/billing': {
      id: '/_shell/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof ShellBillingRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/analytics': {
      id: '/_shell/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ShellAnalyticsRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAnalyticsRoute: typeof ShellAnalyticsRoute
  ShellBillingRoute: typeof ShellBillingRoute
  ShellBookingsRoute: typeof ShellBookingsRoute
  ShellClientsRoute: typeof ShellClientsRoute
  ShellContractsRoute: typeof ShellContractsRoute
  ShellCrmRoute: typeof ShellCrmRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellEventsRoute: typeof ShellEventsRoute
  ShellFloorRoute: typeof ShellFloorRoute
  ShellHelpdeskRoute: typeof ShellHelpdeskRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellTeamRoute: typeof ShellTeamRoute
  ShellVisitorsRoute: typeof ShellVisitorsRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAnalyticsRoute: ShellAnalyticsRoute,
  ShellBillingRoute: ShellBillingRoute,
  ShellBookingsRoute: ShellBookingsRoute,
  ShellClientsRoute: ShellClientsRoute,
  ShellContractsRoute: ShellContractsRoute,
  ShellCrmRoute: ShellCrmRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellEventsRoute: ShellEventsRoute,
  ShellFloorRoute: ShellFloorRoute,
  ShellHelpdeskRoute: ShellHelpdeskRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellTeamRoute: ShellTeamRoute,
  ShellVisitorsRoute: ShellVisitorsRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
